### ISSUE TITLE
msi-gs75 support?

### ISSUE THREAD

**Issue by troyjamz** [ErrorErrorError/msi-gs65-8se-opencore-macos#3] opened 2020-11-07 16:00 UTC
Hi, before I ask for help id I would like to thank you for your efforts made already!

I am a MSI GS75 Stealth 8SF user who has been trying relentlessly to make your open core EFI work on my device. I know that there are some slight differences here and there in terms of hardware but generally speaking they should be similar enough for it to work. But I have yet to be successful!

Initially when I made my bootable USB with your EFI and OSX  I got to the apple logo, the install began and all was fine until it rebooted itself while installing and never continued as it was supposed to after the reboot. 
Now my issue is that I can't get back to the Installer at all. The apple logo appears along with the progress bar but nothing happens and suddenly it reboots and enters Opencore Bootloader again. 

Is there anyway you could possibly help me with solving this or point me in the right direction on how to make this boot on my GS75?

**Comment by erikbdev** [comment] 2020-11-24 09:07
Try again with my latest EFI folder and let me know if it works.

**Comment by fir3burn** [comment] 2020-12-04 12:56
Hi, I'm also have a MSI GS75 8SE.
My problem is  that laptop reboots at random time. Sometimes in the installer, sometimes when is installing, and always before the installation finish.
I'm trying with the folder of 24nov
Any ideas?
Thanks

**Comment by erikbdev** [comment] 2020-12-04 20:03
> Hi, I'm also have a MSI GS75 8SE.
> 
> My problem is  that laptop reboots at random time. Sometimes in the installer, sometimes when is installing, and always before the installation finish.
> 
> I'm trying with the folder of 24nov
> 
> Any ideas?
> 
> Thanks

How long have you let it install? Or do you get an error message?

**Comment by fir3burn** [comment] 2020-12-05 08:38
No error message, just reboot to MSI logo.
The reboot sometimes happens even in the initial menu of the recovery before installing.
It's between 5 and 15 minutes, randomly.

**Comment by erikbdev** [comment] 2020-12-05 12:52
> No error message, just reboot to MSI logo.
> 
> The reboot sometimes happens even in the initial menu of the recovery before installing.
> 
> It's between 5 and 15 minutes, randomly.

How did you create your installer?

**Comment by fir3burn** [comment] 2020-12-05 19:28
Well,
First I try with Clover, but before I've made the instalation, I realized U move to opencore.
Then I formated stick in FAT32, and labeled EFI.
Copy the EFI folder of your gitlab repository to the stick.
Download corpnewt/gibMacOS and execute GibMacOS.bat to download BigSur
Copy the downloaded BaseSystem.dmg and BaseSystem.chunklist to the folder com.apple.recovery.boot in the root of the stick.
In the BIOS I disabled secureboot, VT-D and fastboot
Boot from UEFI into the stick and start the OSX recovery.
In the recovery change the language, start the disk utility to format the target partition to ADFS (first time) and then start recovery process.
I've tried with Catalina too, and the random reboot is present too.
Maybe something with the plist.config?

**Comment by fir3burn** [comment] 2020-12-06 12:44
I'm trying more tests.
I left the laptop in the OSX recovery for an hour without reboots.
Then I tried to format the partition and then the laptop reboots to MSI logo.
I could format the partition only once of 5 times.
I'm trying install OSX in one partition of the internal disk. Maybe is this the problem?

**Comment by fir3burn** [comment] 2020-12-07 05:31
The problem is Samsung PM981 and NVMeFix 1.0,4 still has the random reboot.
I'll try with a external drive. 
Thanks very much for your work @ErrorErrorError

**Comment by erikbdev** [comment] 2020-12-07 05:43
> The problem is Samsung PM981 and NVMeFix 1.0,4 still has the random reboot.
> 
> I'll try with a external drive. 
> 
> Thanks very much for your work @ErrorErrorError

Yup heard about that none causes issues with hackintosh. Maybe upgrade the firmware of the nvme?

**Comment by lilmik** [comment] 2020-12-07 08:37
My laptop is MSI-gs75-8sg. I successfully updated from Catalina to Big Sur with this EFI, although I encountered many long-term unresponsiveness during the process. After the upgrade was completed, I adjusted some of the drivers and reset nvram several times. The system can be used normally.
At present, I still have a small problem that fcp and iMovie cannot exit normally.

**Comment by erikbdev** [comment] 2020-12-07 23:53
> At present, I still have a small problem that fcp and iMovie cannot exit normally.

Hm. I don't seem to have any issues with iMovie. Have you reinstalled/updated iMovie? Is there any crash logs?

**Comment by lilmik** [comment] 2020-12-08 01:28
> > At present, I still have a small problem that fcp and iMovie cannot exit normally.
> 
> Hm. I don't seem to have any issues with iMovie. Have you reinstalled/updated iMovie? Is there any crash logs?

Yes, I have tried to reinstall these two software. The software can exit normally, but it will still take longer than before.

**Comment by lilmik** [comment] 2020-12-08 01:37
I also occasionally encounter the problem that some processes cannot be terminated and cannot be restarted or shutdown.
I think this should be related to the installation method of my system.
I first installed Catalina using Clover, then switched to OC and used Catalina for a while, and finally Use your EFI to update from Catalina to Big Sur.
There should be some caches or some conflicts settings in my system, which caused me to encounter various strange problems. Maybe the next time I install Big Sur directly, there will be no problem.

**Comment by erikbdev** [comment] 2020-12-09 22:26
> There should be some caches or some conflicts settings in my system, which caused me to encounter various strange problems. Maybe the next time I install Big Sur directly, there will be no problem.

Strange. Best bet is to reinstall or also use https://dortania.github.io/OpenCore-Install-Guide/ to make sure it works with your system properly.

**Comment by erikbdev** [comment] 2020-12-10 23:54
Closing since I do not own a gs75 therefore cannot really diagnose this problem more.

**Closed as completed by erikbdev** 2020-12-10 23:54 UTC
